apiVersion: v1
kind: ConfigMap
metadata:
  name: sudoku-config
  namespace: sudoku-game
data:
  FLASK_ENV: "production"
  APP_VERSION: "2.0.0"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "sudoku_db"
  DB_USER: "sudoku"