apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sudoku-game
  namespace: sudoku-game
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: sudoku-game.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sudoku-game
                port:
                  number: 80